### ISSUE TITLE
"String[]" in the docs is rendered as "String" on electronjs.org

### ISSUE THREAD

**Issue by flotwig** [electron/electronjs.org#3034] opened 2019-10-17 16:53 UTC
It seems like writing `String[]` (to denote a list of strings) gets rendered as "String" by electronjs.org's markdown renderer.

For example, see how `additionalArguments` is described on GitHub.com:

https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions

![image](https://user-images.githubusercontent.com/1151760/67030357-3dfde980-f0dd-11e9-88c2-13a93661cfaa.png)

vs. how it looks on electronjs.org:

https://electronjs.org/docs/api/browser-window#new-browserwindowoptions

![image](https://user-images.githubusercontent.com/1151760/67030244-05f6a680-f0dd-11e9-909e-b5a81f15e03f.png)

Which is pretty confusing, since `String` and `String[]` are distinct types.

It looks like `String[]` gets converted to this HTML:

```html
String<a href="/docs/api/optional"></a>
```

**Comment by HashimotoYT** [comment] 2019-10-17 18:38
Duplicate of https://github.com/electron/electron/issues/16034. See #2102 and https://github.com/electron/i18n/pull/596 for more information.

**Closed by HashimotoYT** 2019-10-17 18:38 UTC
