### ISSUE TITLE
404 for /docs/README

### ISSUE THREAD

**Issue by maximtop** [electron/electronjs.org#1165] opened 2018-03-01 09:07 UTC
On page https://electronjs.org/docs/tutorial/quick-start
The following route is returning a 404 HTTP status code: /docs/README

**Comment by sharadshriram** [comment] 2018-03-03 12:17
@maximtop, Cannot reproduce the issue! Tested on Chrome and Edge browsers.

**Comment by TiagoDanin** [comment] 2018-03-03 12:52
@sharadshriram Click in "official guides"

**Comment by vanessayuenn** [comment] 2018-03-05 14:01
Closing due to duplication of #1022

**Closed by vanessayuenn** 2018-03-05 14:01 UTC
Labels: bug, docs
