### ISSUE TITLE
Firefox: no top margin for electron logo in apps section

### ISSUE THREAD

**Issue by co16353sidak** [electron/electronjs.org#2502] opened 2019-04-30 17:53 UTC
url: https://electronjs.org/apps/now

the navbar has the electron logo placed without any margin at the top, therefore it seems mis-aligned with other contents of the navbar.

screenshot:
<img width="1280" alt="Screenshot 2019-04-30 at 11 18 15 PM" src="https://user-images.githubusercontent.com/35738138/56982292-9af0fc00-6b9e-11e9-9761-fa7a81cfa4f5.png">

this seems like an easy fix and I would love to submit a PR with the proposed changes.

**Comment by pierreneter** [comment] 2019-05-21 04:53
I can't reproduce it. Can you check it again?

**Comment by co16353sidak** [comment] 2019-05-21 19:19
Seems like the issue is fixed, or maybe it was an error on my part. not able to reproduce as well. 😅

**Comment by HashimotoYT** [comment] 2019-10-17 18:40
Closing per answer above

**Closed by HashimotoYT** 2019-10-17 18:40 UTC
