### ISSUE TITLE
RSS feed missing from new website

### ISSUE THREAD

**Issue by garar** [electron/electronjs.org#931] opened 2017-12-01 14:00 UTC
Hello!

It seems that new website and new blog don't have RSS feed. Is it intentional? Or is it something that will be added in the future? It was quite useful.

Thanks!

**Comment by pierreneter** [comment] 2017-12-01 19:30
It's not intentional; it will come back soon.

**Comment by pierreneter** [comment] 2017-12-01 19:40
Duplicate of #890

**Comment by tborychowski** [comment] 2017-12-05 13:56
currently there is no way to follow the Electron's blog.

**Closed** 2017-12-13 21:19 UTC
